name: "CI - Build and push with reusable workflow (Development)"

on:
  push:
    branches: [dev]
    paths:
      - ./**
      - .github/workflows/ci_dev.yml
  pull_request:
    branches: [dev]
    paths:
      - ./**
      - .github/workflows/ci_dev.yml
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: TIHLDE/tihlde-workflows/.github/workflows/_ci_ghcr.yml@v1
    with:
      tag-prefix: dev
      push: ${{ github.event_name != 'pull_request' }}
      build-args: |
        NEXT_PUBLIC_URL=https://sporty.tihlde.org/
        NEXT_PUBLIC_VAPID_PUBLIC_KEY=BA2uyd3XH6L0owvEMUYMjqEcadUuZCvnbHHzMVC1zW4nr-UXcBXRhZBPitVCZ-5eO-VQC24xOfWI2oBeozFyiRU
  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    uses: TIHLDE/tihlde-workflows/.github/workflows/_notify_deploy.yml@v1.1.3
    with:
      tag: dev
      environment: dev
    secrets:
      DEPLOY_RECEIVER_TOKEN: ${{ secrets.DEPLOY_RECEIVER_TOKEN }}
